# -*- coding: utf-8 -*-
"""Codigo_Guiado_Clase_1_Fundamentos_Python.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fLA4jq_wk1cv_4M9HpKuP6eZaxjbL0k_

# Código guiado — Clase 1

Este notebook está pensado para ejecutarse lentamente durante la clase.

## Clase 1 - Fundamentos De Python para analítica financiera
"""

# ============================================================
# CLASE 1 - FUNDAMENTOS DE PYTHON PARA ANALITICA FINANCIERA
# Curso: Introduccion a la programacion para analitica financiera
# Profesor: Orlando Joaqui-Barandica
# Entorno recomendado: Google Colab

"""## Como Usar Este Archivo En Clase"""

# ------------------------------------------------------------------
# COMO USAR ESTE ARCHIVO EN CLASE
# ------------------------------------------------------------------
# 1. Abra Google Colab: https://colab.research.google.com/
# 2. Cree un notebook nuevo.
# 3. Copie cada bloque de este script en una celda distinta.
# 4. Ejecute cada celda con Shift + Enter.
# 5. Lea los comentarios antes de ejecutar:
#
# IMPORTANTE:
# - Las lineas que empiezan con # son comentarios. Python las ignora.
# - Los comentarios sirven para explicar el codigo, no afectan el resultado.
# - En Colab conviene ir lento: escribir, ejecutar, mirar el resultado y comentar.
# ------------------------------------------------------------------

"""## 1. Hola Mundo Financiero"""

# 1. HOLA MUNDO FINANCIERO

# print() muestra informacion en pantalla.
# Es la primera funcion que normalmente se usa al aprender un lenguaje.
print("Hola mundo financiero")

# Tambien podemos hacer operaciones directas.
# En un notebook, si una linea queda sola al final de una celda, Colab muestra el resultado.
# En un archivo .py, es mejor usar print() para ver siempre la salida.
print(2 + 2)

# El guion bajo mejora la lectura de numeros grandes.
# Python ignora el guion bajo: 30_000_000 es lo mismo que 30000000.
print(30_000_000 * 0.25)

"""## 2. Variables: Guardar Informacion Con Nombre"""

# 2. VARIABLES: GUARDAR INFORMACION CON NOMBRE

# Una variable es un nombre que guarda un valor.
# En finanzas conviene que el nombre indique que representa el dato.

capital = 30_000_000       # monto del credito o inversion

tasa_ea = 0.25             # tasa efectiva anual del 25%, escrita como decimal
plazo_meses = 48           # plazo del credito en meses
cliente = "Cliente A"      # texto: se escribe entre comillas
tiene_codeudor = True      # booleano: verdadero o falso

# Mostramos las variables.
print("Capital:", capital)
print("Tasa efectiva anual:", tasa_ea)
print("Plazo en meses:", plazo_meses)
print("Cliente:", cliente)
print("Tiene codeudor:", tiene_codeudor)

# Recuerde que tasa_ea = 0.25 significa 25%, no 0.25%.
# En Python las tasas se trabajan normalmente como decimales.

# 3. TIPOS DE DATOS: int, float, str, bool

# type() permite preguntar que tipo de dato tiene una variable.
# Esto es muy importante cuando los datos vienen de formularios, archivos CSV o APIs.

print(type(capital))          # int: numero entero
print(type(tasa_ea))          # float: numero decimal
print(type(plazo_meses))      # int: numero entero
print(type(cliente))          # str: texto
print(type(tiene_codeudor))   # bool: verdadero/falso


# Pregunta: ¿por que cliente no se puede multiplicar por una tasa?

"""## 4. Operadores Aritmeticos Basicos"""

# 4. OPERADORES ARITMETICOS BASICOS

# Python permite escribir formulas financieras casi como se escriben en papel.

saldo = 30_000_000
interes_anual = saldo * tasa_ea
valor_total_anual = saldo + interes_anual

print("Interes anual:", interes_anual)
print("Valor total al final del año:", valor_total_anual)

# Otros operadores utiles:
print("Suma:", 10 + 5)
print("Resta:", 10 - 5)
print("Multiplicacion:", 10 * 5)
print("Division:", 10 / 5)
print("Potencia:", 2 ** 3)  # 2 elevado a la 3 = 8

# La potencia **. Es clave para interes compuesto.

"""## 5. Formato De Resultados: Moneda Y Porcentajes"""

# 5. FORMATO DE RESULTADOS: MONEDA Y PORCENTAJES

# Los resultados sin formato pueden ser dificiles de leer.
print(interes_anual)

# f-string: permite insertar variables dentro de un texto usando llaves {}.
# :,.0f significa: separador de miles y cero decimales.
print(f"Interes anual estimado: ${interes_anual:,.0f}")

# :.2% significa: multiplicar por 100, mostrar 2 decimales y agregar %.
print(f"Tasa efectiva anual: {tasa_ea:.2%}")

# Tambien se puede combinar todo en un pequeño reporte.
print("\n=== REPORTE BASICO DEL CREDITO ===")
print(f"Cliente: {cliente}")
print(f"Capital: ${capital:,.0f}")
print(f"Tasa efectiva anual: {tasa_ea:.2%}")
print(f"Plazo: {plazo_meses} meses")
print(f"Interes anual estimado: ${interes_anual:,.0f}")

# 6. CUIDADO CON input(): TODO ENTRA COMO TEXTO

# input() pide un dato por teclado.
# En Colab aparece una cajita para escribir.
# Pero input() SIEMPRE devuelve texto, incluso si el estudiante escribe numeros.

# Para no detener la ejecucion completa del script, dejamos este bloque apagado.
# En clase, cambie EJECUTAR_INPUT a True si quiere mostrarlo en vivo.

EJECUTAR_INPUT = False

if EJECUTAR_INPUT:
    capital_digitado = input("Ingrese el capital: ")
    print("Valor digitado:", capital_digitado)
    print("Tipo de dato:", type(capital_digitado))

    # Si queremos calcular, debemos convertir a numero.
    capital_digitado = float(capital_digitado)
    print("Tipo despues de convertir:", type(capital_digitado))

# Ejecute primero con texto y muestre que type() dice str.
# Luego convierta con float(). Esa es una fuente comun de errores.

"""## 7. Tasas: De Efectiva Anual A Mensual"""

# 7. TASAS: DE EFECTIVA ANUAL A MENSUAL

# Muchas veces una tasa esta anualizada, pero el calculo se hace mensual.
# Hay una forma aproximada y una forma financieramente equivalente.

tasa_ea = 0.25

# Forma aproximada: dividir entre 12.
tasa_mensual_aprox = tasa_ea / 12

# Forma equivalente: encontrar la tasa mensual que, capitalizada 12 meses,
# reproduce exactamente la tasa efectiva anual.
tasa_mensual_equivalente = (1 + tasa_ea) ** (1 / 12) - 1

print("\n=== TASAS MENSUALES ===")
print(f"Tasa EA: {tasa_ea:.2%}")
print(f"Tasa mensual aproximada: {tasa_mensual_aprox:.4%}")
print(f"Tasa mensual equivalente: {tasa_mensual_equivalente:.4%}")

# Diferencia de intereses en el primer mes sobre un saldo de 30 millones.
saldo = 30_000_000
interes_aprox = saldo * tasa_mensual_aprox
interes_equiv = saldo * tasa_mensual_equivalente
diferencia = interes_aprox - interes_equiv

print(f"Interes mensual aproximado: ${interes_aprox:,.0f}")
print(f"Interes mensual equivalente: ${interes_equiv:,.0f}")
print(f"Diferencia: ${diferencia:,.0f}")


# Mensaje financiero: dividir entre 12 es comun, pero no siempre correcto.
# Python ayuda a hacer la conversion exacta sin esfuerzo adicional.

"""## 8. Interes Simple"""

# 8. INTERES SIMPLE

# Formula: VF = C * (1 + i * n)
# C: capital inicial
# i: tasa por periodo
# n: numero de periodos

capital = 10_000_000
tasa_ea = 0.12
anios = 3

vf_simple = capital * (1 + tasa_ea * anios)

print("\n=== INTERES SIMPLE ===")
print(f"Capital inicial: ${capital:,.0f}")
print(f"Tasa efectiva anual: {tasa_ea:.2%}")
print(f"Plazo: {anios} años")
print(f"Valor futuro simple: ${vf_simple:,.0f}")

# En interes simple, los intereses siempre se calculan sobre el capital inicial.

"""## 9. Interes Compuesto"""

# 9. INTERES COMPUESTO

# Formula: VF = C * (1 + i) ** n
# El operador ** significa potencia.

vf_compuesto = capital * (1 + tasa_ea) ** anios

print("\n=== INTERES COMPUESTO ===")
print(f"Capital inicial: ${capital:,.0f}")
print(f"Tasa efectiva anual: {tasa_ea:.2%}")
print(f"Plazo: {anios} años")
print(f"Valor futuro compuesto: ${vf_compuesto:,.0f}")

# Diferencia entre ambos metodos.
diferencia_vf = vf_compuesto - vf_simple
print(f"Diferencia compuesto - simple: ${diferencia_vf:,.0f}")

# La diferencia puede ser pequeña en plazos cortos y enorme en plazos largos.
# Cambie anios de 3 a 20 y vuelva a ejecutar para que vean el efecto.

"""## 10. Valor Presente"""

# 10. VALOR PRESENTE

# Formula: VP = VF / (1 + i) ** n
# Sirve para traer un valor futuro al dia de hoy.

valor_futuro = 50_000_000
tasa_descuento = 0.10
anios = 5

valor_presente = valor_futuro / (1 + tasa_descuento) ** anios

print("\n=== VALOR PRESENTE ===")
print(f"Valor futuro: ${valor_futuro:,.0f}")
print(f"Tasa de descuento: {tasa_descuento:.2%}")
print(f"Plazo: {anios} años")
print(f"Valor presente: ${valor_presente:,.0f}")

# Capitalizar = llevar al futuro. Descontar = traer al presente.

"""## 11. Listas Como Vectores Sencillos"""

# 11. LISTAS COMO VECTORES SENCILLOS

# En Python, una lista permite guardar varios valores en un solo objeto.
# Por ahora no usaremos ciclos. Solo veremos que una lista puede representar
# varios activos, varias tasas o varios flujos.

tasas_posibles = [0.08, 0.10, 0.12]
flujos = [5_000_000, 6_000_000, 7_000_000]

print("\n=== LISTAS SENCILLAS ===")
print("Tasas posibles:", tasas_posibles)
print("Flujos esperados:", flujos)

# Los indices empiezan en 0.
print(f"Primera tasa: {tasas_posibles[0]:.2%}")
print(f"Segundo flujo: ${flujos[1]:,.0f}")

# Algunas funciones basicas sobre listas.
print(f"Suma de flujos: ${sum(flujos):,.0f}")
print(f"Numero de flujos: {len(flujos)}")
print(f"Promedio simple de flujos: ${sum(flujos) / len(flujos):,.0f}")

# Las listas se trabajaran mejor en sesiones posteriores.
# Hoy basta con que entiendan que una variable tambien puede guardar varios valores.

"""## 12. Mini Caso Guiado: Comparar Dos Alternativas"""

# 12. MINI CASO GUIADO: COMPARAR DOS ALTERNATIVAS

# Problema:
# Un cliente tiene 20 millones para invertir durante 3 años.
# Opcion A: CDT al 9.5% efectivo anual.
# Opcion B: Fondo al 9.0% efectivo anual + bono final de $400.000.
# Pregunta: ¿cual alternativa deja mayor valor futuro?

capital = 20_000_000
plazo_anios = 3

tasa_cdt = 0.095
tasa_fondo = 0.090
bono_fondo = 400_000

vf_cdt = capital * (1 + tasa_cdt) ** plazo_anios
vf_fondo_sin_bono = capital * (1 + tasa_fondo) ** plazo_anios
vf_fondo_total = vf_fondo_sin_bono + bono_fondo

diferencia = vf_cdt - vf_fondo_total
bono_empate = vf_cdt - vf_fondo_sin_bono

print("\n=== COMPARACION DE ALTERNATIVAS ===")
print(f"Capital inicial: ${capital:,.0f}")
print(f"Plazo: {plazo_anios} años")
print(f"CDT - tasa: {tasa_cdt:.2%} | valor futuro: ${vf_cdt:,.0f}")
print(f"Fondo - tasa: {tasa_fondo:.2%} + bono ${bono_fondo:,.0f} | valor futuro: ${vf_fondo_total:,.0f}")
print(f"Diferencia CDT - Fondo: ${diferencia:,.0f}")
print(f"Bono minimo para que el fondo empate al CDT: ${bono_empate:,.0f}")

# En la sesion 2 aprenderemos a hacer que Python tome esta decision con if/else.
# Por ahora, leemos la diferencia:
# - Si diferencia > 0, el CDT gana.
# - Si diferencia < 0, el fondo gana.
# - Si diferencia = 0, empatan.


# Lectura del resultado del mini caso:
if diferencia > 0:
    print("Lectura: el CDT deja mayor valor futuro.")
elif diferencia < 0:
    print("Lectura: el fondo deja mayor valor futuro.")
else:
    print("Lectura: las dos alternativas empatan.")