# -*- coding: utf-8 -*-
"""Solucion_Actividad_Clase_1_Calculadora_Financiera.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AIU2AUI75zm6nHF_wzr0PLKOUbwtt5Ix

# Solución — Actividad Clase 1

Solución de referencia
"""

# Punto 1: variables del caso
capital = 15_000_000
plazo_anios = 4
tasa_cdt = 0.102
tasa_fondo = 0.097
bono_fondo = 450_000

# Punto 2: revisar tipos
print(type(capital))
print(type(plazo_anios))
print(type(tasa_cdt))
print(type(tasa_fondo))
print(type(bono_fondo))

# Punto 3: calculadora basica para el CDT
vf_simple_cdt = capital * (1 + tasa_cdt * plazo_anios)
vf_compuesto_cdt = capital * (1 + tasa_cdt) ** plazo_anios
diferencia_compuesto_simple = vf_compuesto_cdt - vf_simple_cdt

print("=== CDT: SIMPLE VS COMPUESTO ===")
print(f"Capital inicial: ${capital:,.0f}")
print(f"Tasa CDT: {tasa_cdt:.2%}")
print(f"Plazo: {plazo_anios} años")
print(f"VF simple: ${vf_simple_cdt:,.0f}")
print(f"VF compuesto: ${vf_compuesto_cdt:,.0f}")
print(f"Diferencia: ${diferencia_compuesto_simple:,.0f}")

# Punto 4: comparar CDT vs fondo
vf_cdt = vf_compuesto_cdt
vf_fondo_sin_bono = capital * (1 + tasa_fondo) ** plazo_anios
vf_fondo_total = vf_fondo_sin_bono + bono_fondo

print("=== COMPARACION CDT VS FONDO ===")
print(f"CDT compuesto: ${vf_cdt:,.0f}")
print(f"Fondo sin bono: ${vf_fondo_sin_bono:,.0f}")
print(f"Fondo con bono: ${vf_fondo_total:,.0f}")

# Punto 5: valor presente del valor futuro del fondo
tasa_descuento = 0.10
vp_fondo = vf_fondo_total / (1 + tasa_descuento) ** plazo_anios

print(f"Tasa de descuento: {tasa_descuento:.2%}")
print(f"VP del fondo: ${vp_fondo:,.0f}")

# Punto 6 y 7: decision y bono de empate
bono_empate = vf_cdt - vf_fondo_sin_bono
diferencia = vf_cdt - vf_fondo_total

print("=== DECISION ===")
print(f"Bono minimo para empatar: ${bono_empate:,.0f}")
print(f"Diferencia CDT - Fondo: ${diferencia:,.0f}")

if diferencia > 0:
    print("Conviene el CDT: deja mayor valor futuro.")
elif diferencia < 0:
    print("Conviene el fondo: deja mayor valor futuro con el bono incluido.")
else:
    print("Las dos alternativas empatan.")